### ISSUE TITLE
Incremental parsing and error recovery ?

### ISSUE THREAD

**Issue by bgnx** [pvdz/tenko#3]
Seems like tenko does not have these features. 
Have you seen tree-sitter (https://www.youtube.com/watch?v=Jes3bD6P0To) ? What was the reason to create a new parser without incremental parsing and error recovery ?

**Comment by pvdz** [comment]
You are correct!

Error resilience is on my wishlist and something I intend to tackle at some point. It's something that may just work without significant problems (any thrown error goes through `THROW`, which may just ignore the error rather than `throw`). I just haven't gone through that hell hole yet.

Incremental parsing is a pita. Didn't know I had to have a reason for it but there you go:

- I'm just one guy
- This was a pet project, you don't need to use it
- I didn't get paid to work on this
- I haven't seen that video and do not know what "tree-sitter" is
- Didn't know there were requirements to building a parser these days

(__Here's a tip: next time perhaps try to phrase that last question in a way that feels less like blame and more like curiosity.__)

If you feel strongly about a feature I would suggest to open issues for them individually and stick to one feature. Perhaps even suggest how, or better yet, a PR. I'm going to close this one. Thank you.

**Comment by pvdz** [comment]
Btw, thanks for the suggestion. Looks interesting. I'll add it to my playlist :)

**Comment by pvdz** [comment]
Thought you may wanted to know about https://github.com/escaya/escaya
